version: '3.3'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/src
    command: supervisor -e '.' index.js
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD = 1
      - MYSQL_DATABASE = world
      - MYSQL_ROOT_PASSWORD = null
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD = 1
      - MYSQL_DATABASE = world
      - MYSQL_ROOT_PASSWORD = null
    ports:
      - "8081:80"