version: '3.3'
services:
  app:
    build:
      context: .
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=world
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=world
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:80"

volumes:
  mysql_data: